### ISSUE TITLE
HiC-Spector

### ISSUE THREAD

**Issue by Phlya** [kundajelab/3DChromatin_ReplicateQC#11]
And HiC-Spector doesn't work for me either with the following error:

```
Traceback (most recent call last):
  File "/exports/eddie3_homes_local/s1529682/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 209, in <module>
    main()
  File "/exports/eddie3_homes_local/s1529682/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 202, in main
    get_reproducibility(M1,M2,int(sys.argv[6]))
  File "/exports/eddie3_homes_local/s1529682/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 163, in get_reproducibility
    b1_extend[i_nz1,i]=b1[:,i]
IndexError: index 2 is out of bounds for axis 1 with size 2
```

**Comment by oursu** [comment]
Hi @Phlya 

Do you get this error on the example files provided with "3DChromatin_ReplicateQC"? I am not getting this error when running the examples, so if the error comes from a different set of files, can you please post a minimal set of data that recapitulates the error and then I can try to fix it? 

Thanks!

**Comment by chesi** [comment]
I have the same problem, did you ever figure it out?
This is my command and log:
~/programs/anaconda2/bin/3DChromatin_ReplicateQC concordance --metadata_pairs metadata.pairs --outdir output_rHMC3_chr22 --methods HiC-Spector
Step: concordance | Mon Feb 24 10:04:46 2020 | computing concordance between rHMC3_1_4f and rHMC3_2_4f
Step: concordance | Mon Feb 24 10:04:47 2020 | computing concordance between rHMC3_2_4f and rHMC3_3_4f
Step: concordance | Mon Feb 24 10:04:47 2020 | computing concordance between rHMC3_1_4f and rHMC3_3_4f
Traceback (most recent call last):
  File "/home/chesia/programs/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 209, in <module>
    main()
  File "/home/chesia/programs/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 202, in main
    get_reproducibility(M1,M2,int(sys.argv[6]))
  File "/home/chesia/programs/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 163, in get_reproducibility
    b1_extend[i_nz1,i]=b1[:,i]
IndexError: index 17 is out of bounds for axis 1 with size 17
Traceback (most recent call last):
  File "/home/chesia/programs/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 209, in <module>
    main()
  File "/home/chesia/programs/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 202, in main
    get_reproducibility(M1,M2,int(sys.argv[6]))
  File "/home/chesia/programs/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 163, in get_reproducibility
    b1_extend[i_nz1,i]=b1[:,i]
IndexError: index 17 is out of bounds for axis 1 with size 17
Traceback (most recent call last):
  File "/home/chesia/programs/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 209, in <module>
    main()
  File "/home/chesia/programs/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 202, in main
    get_reproducibility(M1,M2,int(sys.argv[6]))
  File "/home/chesia/programs/3DChromatin_ReplicateQC/wrappers/HiC-Spector/run_reproducibility_v1.py", line 163, in get_reproducibility
    b1_extend[i_nz1,i]=b1[:,i]
IndexError: index 17 is out of bounds for axis 1 with size 17

**Comment by chesi** [comment]
I solved it by reducing the number of eigenvectors for HiC-Spector in the parameters file.
