### ISSUE TITLE
installing error: Couldn't find index page for 'setuptools_cython' (maybe misspelled?)

### ISSUE THREAD

**Issue by YiweiNiu** [kundajelab/3DChromatin_ReplicateQC#17]
Hi,

I am trying to install `3DChromatin_ReplicateQC`, but got the following error

```sh
$ ~/software/anaconda2/bin/pip install 3DChromatin_ReplicateQC/
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing ./3DChromatin_ReplicateQC
Requirement already satisfied: numpy>=1.9 in ./anaconda2/lib/python2.7/site-packages (from 3DChromatin-ReplicateQC==0.0.1) (1.16.4)
Requirement already satisfied: matplotlib>=1.5.0 in ./anaconda2/lib/python2.7/site-packages (from 3DChromatin-ReplicateQC==0.0.1) (1.5.3)
Requirement already satisfied: h5py in ./anaconda2/lib/python2.7/site-packages (from 3DChromatin-ReplicateQC==0.0.1) (2.9.0)
Collecting hifive==1.5.6
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/87/db/352ffd43f2ac26a6071b42ba7ad489d1c4328c536dc1099e0fa99b6fa43a/hifive-1.5.6.tar.gz (1.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/niuyw/software/anaconda2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nk4ypx/hifive/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nk4ypx/hifive/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-Uv0KGo
         cwd: /tmp/pip-install-nk4ypx/hifive/
    Complete output (26 lines):
    Couldn't find index page for 'setuptools_cython' (maybe misspelled?)
    No local packages or download links found for setuptools-cython
    install_dir .
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nk4ypx/hifive/setup.py", line 189, in <module>
        setup_package()
      File "/tmp/pip-install-nk4ypx/hifive/setup.py", line 146, in setup_package
        setup(**metadata)
      File "/home/niuyw/software/anaconda2/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/niuyw/software/anaconda2/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/home/niuyw/software/anaconda2/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/home/niuyw/software/anaconda2/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 544, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/home/niuyw/software/anaconda2/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 786, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/home/niuyw/software/anaconda2/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 798, in obtain
        return installer(requirement)
      File "/home/niuyw/software/anaconda2/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/dist.py", line 293, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/niuyw/software/anaconda2/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 576, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-cython')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Any suggestions would be highly appreciated.

**Comment by oursu** [comment]
Hi @YiweiNiu !
It seems the problem occurs when trying to install hifive https://github.com/bxlab/hifive, which requires python 2.7. I would check with them about any updates on how to install their code. In the meantime, if you do want to try the rest of the methods implemented here, you can comment out the section that refers to Quasar in the installation file at https://github.com/kundajelab/3DChromatin_ReplicateQC/blob/master/install_scripts/install_3DChromatin_ReplicateQC.sh (lines 123-132).

Please let me know how else I can help.

Thanks, 
Oana

**Comment by YiweiNiu** [comment]
Hi Oana,

Thank you for your quick reply!

Finally I installed `hifive` through `conda`. By the way, `hirep` had been [removed from bioconductor](https://github.com/TaoYang-dev/hicrep/issues/67).

As `3DChromatin_ReplicateQC` includes multiple Python/R packages, I suggest that you could pack them through conda or docker.

Bests,
Yiwei
