### ISSUE TITLE
AttributeError when running example script

### ISSUE THREAD

**Issue by stayingsong** [kundajelab/3DChromatin_ReplicateQC#4]
Hello, I am running into the following error after installing the pipeline and testing it on the example data.  Any insights into what might be causing the issue?  Thanks!

-bash-4.1$ python 3DChromatin_ReplicateQC.py run_all --metadata_samples examples/metadata.samples --metadata_pairs examples/metadata.pairs --bins examples/Nodes.w40000.bed.gz --outdir examples/output
Traceback (most recent call last):
  File "3DChromatin_ReplicateQC.py", line 709, in <module>
    main()
  File "3DChromatin_ReplicateQC.py", line 705, in main
    command_methods[command](**args)
  File "3DChromatin_ReplicateQC.py", line 683, in run_all
    split_by_chromosome(metadata_samples,bins,re_fragments,methods,outdir,running_mode,subset_chromosomes)
  File "3DChromatin_ReplicateQC.py", line 156, in split_by_chromosome
    subp.check_output(['bash','-c','mkdir -p '+outdir+'/scripts'])
AttributeError: 'module' object has no attribute 'check_output'

**Comment by stayingsong** [comment]
Hi, nevermind, I figured it out, I was using the wrong distro of anaconda/python.  However I ran into a new error while running the example data:

Filtering fends... Removed 1204 of 2487 bins
**/netapp/sali/msong/libraries/anaconda2/bin/python: can't open file '/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/software/hifive/bin/find_quasar_transform': [Errno 2] No such file or directory**
Traceback (most recent call last):
  File "/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/software/genomedisco/reproducibility_analysis/plot_quasar_transform.py", line 68, in <module>
    main()
  File "/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/software/genomedisco/reproducibility_analysis/plot_quasar_transform.py", line 44, in main
    infile1 = h5py.File(args.transform, 'r')
  File "/netapp/sali/msong/libraries/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/netapp/sali/msong/libraries/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (Unable to open file: name = '/netapp/sali/msong/libraries/3dchromatin_replicateqc-master/examples/output/data/forquasar/hic001.quasar_transform', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

It seems that for the HiFive pipeline here (https://github.com/bxlab/hifive/tree/master/bin), there are no longer bin files for "find_quasar_transform" and "find_quasar_quality_score"?

In fact, I think in this commit (https://github.com/bxlab/hifive/commit/c65a675733513221402f8a90731e03461a2ddca3#diff-c1111bd512b29e821b120b86446026b8) 7 days ago, they combined those two functionalities into the "hifive" binary.  Would you suggest manually installing an older version of HiFive to work with your pipeline for now?  Thanks!

**Comment by stayingsong** [comment]
Update--okay, so deleting the "hifive" folder under "software" and replacing it with an older version of hifive before the most recent commits fixed the issue, but now there's a new bug:

2426265 validly-mapped read pairs loaded.
2426265 total validly-mapped read pairs loaded. 223753 valid bin pairs
Parsing fend pairs... Done  2426265 cis reads, 0 trans reads
Filtering fends... Removed 1204 of 2487 bins
Traceback (most recent call last):
  File "/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/software/genomedisco/reproducibility_analysis/plot_quasar_transform.py", line 68, in <module>
    main()
  File "/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/software/genomedisco/reproducibility_analysis/plot_quasar_transform.py", line 47, in main
    data1 = load_data(infile1, chroms, resolutions)
  File "/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/software/genomedisco/reproducibility_analysis/plot_quasar_transform.py", line 24, in load_data
    dist = infile['dist.%s.%i' % (chrom, res)][...]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/netapp/sali/msong/libraries/anaconda2/lib/python2.7/site-packages/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (Object 'dist.21.40000' doesn't exist)"

Not sure if this is a consequence of the slights differences in "hifive" version, but any insight would be appreciated.  Thanks!

**Comment by oursu** [comment]
Hi,
I apologize for the delays. 

Indeed, hifive has gone through some changes and re-factoring, and these have been incorporated into 3DChromatin_ReplicateQC. 
Please re-clone this repository (3DChromatin_ReplicateQC) and re-run the install script.

Then, QuASAR should be functional. 

Let me know if you still get errors.

**Comment by stayingsong** [comment]
Hello,

I reinstalled anaconda2 as well as 3DChromatin_ReplicateQC from scratch, and am running into this error with the example still:

3DChromatin_ReplicateQC | Tue Dec 12 00:27:31 2017 | Splitting nodes chr21
/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/examples/output/scripts/split/nodes/chr21.nodes.split_files_by_chromosome.sh
3DChromatin_ReplicateQC | Tue Dec 12 00:27:31 2017 | Splitting HIC001 chr21
/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/examples/output/scripts/split/HIC001/chr21.HIC001.split_files_by_chromosome.sh
3DChromatin_ReplicateQC | Tue Dec 12 00:27:31 2017 | Splitting HIC002 chr21
/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/examples/output/scripts/split/HIC002/chr21.HIC002.split_files_by_chromosome.sh
3DChromatin_ReplicateQC | Tue Dec 12 00:27:32 2017 | Splitting nodes chr22
/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/examples/output/scripts/split/nodes/chr22.nodes.split_files_by_chromosome.sh
3DChromatin_ReplicateQC | Tue Dec 12 00:27:32 2017 | Splitting HIC001 chr22
/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/examples/output/scripts/split/HIC001/chr22.HIC001.split_files_by_chromosome.sh
3DChromatin_ReplicateQC | Tue Dec 12 00:27:33 2017 | Splitting HIC002 chr22
/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/examples/output/scripts/split/HIC002/chr22.HIC002.split_files_by_chromosome.sh
Tue Dec 12 00:27:34 2017
running QuASAR-QC | computing QC for HIC001
examples/output/scripts/QuASAR-QC/HIC001/HIC001.QuASAR-QC.sh
Quasar file(s) are not of the correct filetype.
Traceback (most recent call last):
  File "/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/wrappers/QuASAR/quasar_split_by_chromosomes_qc.py", line 29, in <module>
    main()
  File "/netapp/sali/msong/libraries/3DChromatin_ReplicateQC-master/wrappers/QuASAR/quasar_split_by_chromosomes_qc.py", line 10, in main
    scorefile = open( sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: 'examples/output/results/qc/HIC001/QuASAR-QC/HIC001.QuASAR-QC.scores.txt'
Traceback (most recent call last):
  File "3DChromatin_ReplicateQC.py", line 758, in <module>
    main()
  File "3DChromatin_ReplicateQC.py", line 754, in main
    command_methods[command](**args)
  File "3DChromatin_ReplicateQC.py", line 734, in run_all
    get_qc(metadata_samples,methods,parameters_file,outdir,running_mode,concise_analysis,subset_chromosomes,timing)
  File "3DChromatin_ReplicateQC.py", line 491, in get_qc
    quasar_qc_wrapper(outdir,None,samplename,running_mode,timing)
  File "3DChromatin_ReplicateQC.py", line 307, in quasar_qc_wrapper
    run_script(script_comparison_file,running_mode)
  File "3DChromatin_ReplicateQC.py", line 235, in run_script
    output=subp.check_output(['bash','-c',script_name])
  File "/netapp/sali/msong/libraries/anaconda2/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '-c', 'examples/output/scripts/QuASAR-QC/HIC001/HIC001.QuASAR-QC.sh']' returned non-zero exit status 1

Do you have any insight into why QuASAR is still having an error?  Or what command would you use to run the script with all the modules except QuASAR?

Thanks!

Michael

**Comment by oursu** [comment]
Hi Michael,

I am checking this to figure out how to fix it.

To answer your second question, you can set "--methods GenomeDISCO,HiC-Spector,HiCRep" to not run QuASAR. However, QuASAR is a very good method as well, so I will get back asap about how to fix the above error.

Thanks,
Oana

**Comment by jamesdalg** [comment]
I also get the same issue. What else can I try, if I might ask?
(/data/CCRBioinfo/dalgleishjl/3DChromatin_ReplicateQC_env/) bash-4.1$ python 3DChromatin_ReplicateQC.py qc --methods GenomeDISCO,HiC-Spector,HiCRep --metadata_samples examples/metadata.samples --outdir examples/output
Mon Dec 18 17:52:32 2017
running QuASAR-QC | computing QC for HIC001
examples/output/scripts/QuASAR-QC/HIC001/HIC001.QuASAR-QC.sh
Quasar file(s) are not of the correct filetype.
Traceback (most recent call last):
  File "/gpfs/gsfs2/users/CCRBioinfo/dalgleishjl/3DChromatin_ReplicateQC/wrappers/QuASAR/quasar_split_by_chromosomes_qc.py", line 29, in <module>
    main()
  File "/gpfs/gsfs2/users/CCRBioinfo/dalgleishjl/3DChromatin_ReplicateQC/wrappers/QuASAR/quasar_split_by_chromosomes_qc.py", line 10, in main
    scorefile = open( sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: 'examples/output/results/qc/HIC001/QuASAR-QC/HIC001.QuASAR-QC.scores.txt'
Traceback (most recent call last):
  File "3DChromatin_ReplicateQC.py", line 758, in <module>
    main()
  File "3DChromatin_ReplicateQC.py", line 754, in main
    command_methods[command](**args)
  File "3DChromatin_ReplicateQC.py", line 491, in get_qc
    quasar_qc_wrapper(outdir,None,samplename,running_mode,timing)
  File "3DChromatin_ReplicateQC.py", line 307, in quasar_qc_wrapper
    run_script(script_comparison_file,running_mode)
  File "3DChromatin_ReplicateQC.py", line 235, in run_script
    output=subp.check_output(['bash','-c',script_name])
  File "/data/CCRBioinfo/dalgleishjl/3DChromatin_ReplicateQC_env/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '-c', 'examples/output/scripts/QuASAR-QC/HIC001/HIC001.QuASAR-QC.sh']' returned non-zero exit status 1
(/data/CCRBioinfo/dalgleishjl/3DChromatin_ReplicateQC_env/) bash-4.1$

**Comment by oursu** [comment]
Hi, 

Please re-clone this repository and re-run the install script. Then everything should run correctly. There have been some bugs in incorporating QuASAR, and these have now been fixed.

In addition, please make sure to read the (updated) README, which describes how to run the individual steps in 3DChromatin_ReplicateQC (https://github.com/kundajelab/3DChromatin_ReplicateQC#running-3dchromatin_replicateqc-step-by-step). Let me know if after that you still run into errors.

Thanks.

**Comment by oursu** [comment]
I will close this issue. Please re-open it if you still have issues.
